# Generated by Django 2.2.25 on 2021-12-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0033_profile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='https://gate.smsaero.ru/v2/', max_length=64)),
                ('login', models.CharField(blank=True, default='', max_length=32)),
                ('key', models.CharField(blank=True, default='', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sent', models.DateField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site')),
            ],
        ),
    ]
