# Generated by Django 2.2.25 on 2022-01-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='sign',
            field=models.CharField(blank=True, default='Church22', max_length=32),
        ),
    ]
