# Generated by Django 2.2.26 on 2022-01-24 10:06

from django.db import migrations


def set_site(apps, schema_editor):
    People = apps.get_model('mailing', 'people')
    Site = apps.get_model('api', 'site')
    site = Site.objects.first()
    People.objects.all().update(site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_smsconfig_sign'),
    ]

    operations = [
        migrations.RunPython(set_site, reverse_code=migrations.RunPython.noop),
    ]
