# Generated by Django 2.2.27 on 2023-01-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_set_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Напоминать'),
        ),
        migrations.AddField(
            model_name='people',
            name='notify_sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего напоминания'),
        ),
        migrations.AddField(
            model_name='smsconfig',
            name='text_notify',
            field=models.TextField(blank=True, default='', verbose_name='Напоминание'),
        ),
        migrations.AlterField(
            model_name='people',
            name='sent',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего поздравления'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Поздравление'),
        ),
    ]
