# Generated by Django 2.2.27 on 2023-02-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20230110_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('site', 'fio')},
        ),
    ]
