GET https://api.electis.ru/profile/
Authorization: Basic test testtest

###
GET http://127.0.0.1:8010/profile/
Authorization: Basic test testtest

###
GET https://https.home.electis.ru/profile/
Authorization: Basic test testtest

###
