# Generated by Django 2.2.11 on 2020-03-25 11:32

from django.db import migrations
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token


def create_tokens(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_social_email'),
    ]

    operations = [
        migrations.RunPython(create_tokens),
    ]
