# Generated by Django 2.2.11 on 2020-04-14 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_news_newssection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='News',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
