# Generated by Django 2.2.11 on 2020-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_newssection_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
