# Generated by Django 2.2.11 on 2020-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
