# Generated by Django 2.2.11 on 2020-05-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
    ]
