# Generated by Django 2.2.11 on 2020-05-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_news_author_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('position', 'name')},
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.SmallIntegerField(default=100),
        ),
    ]
