# Generated by Django 2.2.17 on 2020-12-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_profile_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Барнаул', max_length=64)),
                ('domain', models.CharField(default='church22.ru', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site'),
        ),
        migrations.AddField(
            model_name='main',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site'),
        ),
        migrations.AddField(
            model_name='news',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site'),
        ),
        migrations.AddField(
            model_name='newssection',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site'),
        ),
        migrations.AddField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Site'),
        ),
    ]
