# Generated by Django 2.2.17 on 2020-12-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_site_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='site',
        ),
    ]
