# Generated by Django 2.2.17 on 2021-02-09 02:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_news_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='no_redirect_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='news',
            name='meter',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
