# Generated by Django 2.2.17 on 2021-03-02 02:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210209_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotContact',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('last_message', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='meter',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='')),
                ('crontab', models.CharField(blank=True, default='', help_text='m/h/dM/MY/dW', max_length=255)),
                ('contacts', models.ManyToManyField(to='api.BotContact')),
            ],
        ),
    ]
