# Generated by Django 2.2.17 on 2021-03-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210302_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='contacts',
        ),
        migrations.AddField(
            model_name='botmessage',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BotContact'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='crontab',
            field=models.CharField(blank=True, default='*/*/*/*/*', help_text='m/h/dM/MY/dW', max_length=255),
        ),
    ]
