# Generated by Django 2.2.17 on 2021-03-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210303_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='path_prefix',
            field=models.CharField(default='', help_text='biysk/', max_length=64),
        ),
    ]
