# Generated by Django 2.2.17 on 2021-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_site_path_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
