# Generated by Django 2.2.17 on 2021-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210405_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='on_map',
            field=models.TextField(blank=True, default=''),
        ),
    ]
