# Generated by Django 2.2.17 on 2021-04-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_main_on_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='requisite',
            field=models.TextField(blank=True, default=''),
        ),
    ]
