# Generated by Django 2.2.17 on 2021-04-05 15:31

import django.core.validators
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_main_requisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='all_command',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg'))]),
        ),
    ]
