# Generated by Django 2.2.26 on 2022-02-11 02:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='commands',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
