# Generated by Django 2.2.27 on 2022-03-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_config_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssection',
            name='media',
            field=models.CharField(blank=True, choices=[('news', 'news'), ('media', 'media')], default='news', max_length=16),
        ),
    ]
