# Generated by Django 2.2.27 on 2022-03-05 02:16

from django.db import migrations


def fill_media(apps, schema_editor):
    Media = apps.get_model('api', 'Media')
    Site = apps.get_model('api', 'Site')
    NewsSection = apps.get_model('api', 'NewsSection')
    media, _ = Media.objects.get_or_create(title='news', site=Site.objects.first())
    NewsSection.objects.filter(media__isnull=True).update(media=media)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220305_0916'),
    ]

    operations = [
        migrations.RunPython(fill_media, migrations.RunPython.noop),
    ]
