# Generated by Django 2.2.27 on 2022-07-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_newssection_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssection',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='botcontact',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='newssection',
            name='media',
            field=models.CharField(blank=True, choices=[('news', 'news'), ('media', 'media'), ('books', 'books')], default='news', max_length=16),
        ),
    ]
