# Generated by Django 3.2.17 on 2023-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220706_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='commands',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='config',
            name='tgram',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='news',
            name='meter',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
