# Generated by Django 3.2.17 on 2023-02-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20230203_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
